stages:
- name: Build and Push
  steps:
  - publishImageConfig:
      dockerfilePath: ./stripes-deploy/Dockerfile
      buildContext: ./
      tag: folio/stripes-pipeline:stripes-pipeline-${CICD_EXECUTION_SEQUENCE}
      registry: pipeline-docker-registry
    envFrom:
      - sourceName: tenant-config
        sourceKey: TENANT_ID
        targetKey: tenant
      - sourceName: tenant-config
        sourceKey: OKAPI_URL
        targetKey: okapi
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
      PLUGIN_BUILD_ARGS_FROM_ENV: tenant=TENANT_ID,okapi=OKAPI_URL
    when:
      branch: {}
      event: {}
  when:
    branch: {}
    event: {}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./stripes-deploy/stripes-deployment.yaml
    when:
      branch: {}
      event: {}
  when:
    branch: {}
    event: {}
timeout: 60
branch:
  include:
  - stripes-pipeline
notification: {}
