stages:
- name: Build and Push
  steps:
  - publishImageConfig:
      dockerfilePath: ./docker/Dockerfile
      buildContext: ./
      tag: docker.dev.folio.org/platform-complete:concorde-${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: docker.dev.folio.org
    env:
      PLUGIN_BUILD_ARGS_FROM_ENV: OKAPI_URL, TENANT_ID
    envFrom:
    - sourceName: tenant-config
      sourceKey: TENANT_ID
    - sourceName: tenant-config
      sourceKey: OKAPI_URL
    cpuRequest: 300m
    cpuLimit: 1500m
    memoryRequest: 10Gi
    memoryLimit: 10Gi
- name: Deploy
  steps:
  - applyAppConfig:
      catalogTemplate: p-rlq5p:concorde-helmcharts-platform-complete
      version: 0.1.12
      answers:
        image.repository: docker.dev.folio.org/platform-complete
        image.tag: concorde-${CICD_EXECUTION_SEQUENCE}
        ingress.enabled: "true"
        ingress.hosts[0].host: concorde.ci.folio.org
        ingress.hosts[0].paths[0]: /
        postJob.enabled: "true"
        resources.limits.cpu: 700m
        resources.limits.memory: 786Mi
      name: platform-complete
      targetNamespace: concorde
timeout: 60
branch:
  include:
  - concorde-rancher
notification: {}
