stages:
  - name: Build and Push
    steps:
      - publishImageConfig:
          dockerfilePath: ./docker/Dockerfile
          buildContext: ./
          tag: docker.dev.folio.org/platform-complete:core-functional-latest
          pushRemote: true
          registry: docker.dev.folio.org
        env:
          PLUGIN_BUILD_ARGS_FROM_ENV: OKAPI_URL, TENANT_ID
        envFrom:
          - sourceName: tenant-config
            sourceKey: TENANT_ID
          - sourceName: tenant-config
            sourceKey: OKAPI_URL
        cpuLimit: 1500m
        memoryLimit: 8Gi
        cpuRequest: 100m
        memoryRequest: 100Mi
  - name: Deploy
    steps:
      - applyAppConfig:
          catalogTemplate: p-9mwdx:core-functional-helmcharts-mod-circulation
          version: 0.1.7
          answers:
            image.repository: docker.dev.folio.org/platform-complete
            image.tag: unam-latest
            ingress.enabled: true
            ingress.hosts[0].host: core-functional.ci.folio.org
            ingress.hosts[0].paths[0]: /
            resources.limits.cpu: 200m
            resources.limits.memory: 300Mi
            postJob.enabled: false
          name: platform-complete
          targetNamespace: core-functional
timeout: 60
branch:
  include:
    - rancher-core-functional
notification: {}